name: UnnamedGunGame
version: '0.2-ALPHA'
main: me.onatic.unnamedgungame.UnnamedGunGame
api-version: '1.20'
depend: [WorldGuard]
permissions:
  unnamedgungame.throwbarricade:
    description: Allows player to throw barricades
    default: op
commands:
  ugg:
    description: Main command for the UnnamedGunGame plugin